// scroll below towards the end to see the code without any comments


import java.util.Scanner;

public class Numberguessgame{
    String name; // initializes a variable name and num
    int num;
    public Numberguessgame(String name, int num){
        this.name = name; // using this method as taught in class we can refer to the variable outside and connect the two
        this.num = num;
    }
    public String getName() { // method used to call the name whenever needed
        return name;
    }
    public int getNum() { //same as getName
        return num;
    }
    public static int mainNum;
    static{ // mainNum will not be changed after first initialization so thats why it is kept static
        mainNum = (int) (Math.random() * 10); // method to print a random num as shown in the q paper
    }
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in); //Scanner initialization
        Numberguessgame[] players = new Numberguessgame[3]; //makes a players array 

        for (int i = 0; i < players.length; i++) {
            System.out.println("Enter the name for player " + (i + 1) + ": "); // Entering player name
            String name = scanner.nextLine();
            players[i] = new Numberguessgame(name, 0);
            
            System.out.println("Guess a number " + players[i].name + ": "); // player guessed num
            int num = scanner.nextInt();
            scanner.nextLine();
            players[i] = new Numberguessgame(name, num);
        }

        int count = 0; // this count is made so if no one wins the count will remain zero and later we can print "No one wins" or "everyone wins" using the if else statements
        for (int i = 0; i < players.length; i++) {
        if(players[i].getNum() == mainNum){
            System.out.println(players[i].getName() + " wins"); // prints name of the player whose guess was correct
            count = count + 1;
        }
        }

        if(count == 0){
            System.out.println("\n No one wins!");
        }
        else if(count == 3){
            System.out.println("\n Everyone wins!");
        }

        System.out.println("Winning Number: " + mainNum); // Number generated by the random function

        System.out.println("\nPlayer Details:");
        for (int i = 0; i < players.length; i++) {
            System.out.println("Name = " + players[i].getName() + ", Number = " + players[i].getNum());
        }

        scanner.close();
    }
}



import java.util.Scanner;

public class Numberguessgame {
    String name;
    int num;

    public Numberguessgame(String name, int num) {
        this.name = name;
        this.num = num;
    }

    public String getName() {
        return name;
    }

    public int getNum() {
        return num;
    }

    public static int mainNum;

    static {
        mainNum = (int) (Math.random() * 10);
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Numberguessgame[] players = new Numberguessgame[3];

        for (int i = 0; i < players.length; i++) {
            System.out.println("Enter the name for player " + (i + 1) + ": ");
            String name = scanner.nextLine();
            players[i] = new Numberguessgame(name, 0);

            System.out.println("Guess a number " + players[i].name + ": ");
            int num = scanner.nextInt();
            scanner.nextLine();
            players[i] = new Numberguessgame(name, num);
        }

        int count = 0;
        for (int i = 0; i < players.length; i++) {
            if (players[i].getNum() == mainNum) {
                System.out.println(players[i].getName() + " wins");
                count = count + 1;
            }
        }

        if (count == 0) {
            System.out.println("\n No one wins!");
        } else if (count == 3) {
            System.out.println("\n Everyone wins!");
        }

        System.out.println("Winning Number: " + mainNum);

        System.out.println("\nPlayer Details:");
        for (int i = 0; i < players.length; i++) {
            System.out.println("Name = " + players[i].getName() + ", Number = " + players[i].getNum());
        }

        scanner.close();
    }
}

